
server:
  port: 8086

spring:
  datasource:
    url: jdbc:h2:mem:testdb1
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true

  h2:
    console:
      enabled: true
      path: /h2-console
  application:
    name: policy-service


